### ISSUE TITLE
libxmljs - test performance, find async solution

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#13]
This lib isn't async. We want this xml comfoolery to be on a worker thread. If the server is doing a lot of XML parsing, is it going to jam up?

**Comment by hallahan** [comment]
Consider this fork:

https://github.com/gagern/libxmljs

**Comment by mojodna** [comment]
I usually end up using [xml2js](https://www.npmjs.com/package/xml2js), which has a callback-driven API (i.e. looks async, but appears to default to not be; even when in async mode, it just breaks up the work rather than parsing in the threadpool).

However, for macrocosm, I ended up using [xml2json](https://www.npmjs.com/package/xml2json) instead, mainly because the output much more closely matches the JSON API implemented there. It _does not_ have an async API.

**Comment by hallahan** [comment]
Might be a good idea to benchmark a little bit...

One thing to influence, in npm:

_xml2js_ 2,313,886 downloads in the last month
_libxmljs_ 34,122 downloads in the last month

Clearly, xml2js has drastically more usage in the node community.

**Comment by hallahan** [comment]
This is going to need to bump up in priority. Looking at data sets from current field pilots, OSM aggregation is __painfully__ slow as the survey submissions get large. I think a better XML library may drastically improve performance.

**Comment by hallahan** [comment]
For creating `osc`, I'm going to try out __xml2js__.

**Comment by mojodna** [comment]
See also https://github.com/mojodna/changeset-replay-tool/blob/master/generate-osc.js (which uses a mixture of raw strings + `xmlbuilder`)

**Comment by hallahan** [comment]
Looks like @mojodna uses two components that are a part of __xml2js__

https://github.com/isaacs/sax-js
https://github.com/oozcitak/xmlbuilder-js

I'm thinking ill follow suit, since I'm more used to SAX interface anyway. Should be more performant too.

**Comment by hallahan** [comment]
We use xml2js in osm/submit-changesets.js and this solution is fantastic. Because this slower module is used for creating OSM aggregations, I think its fine keeping with what we are doing right now, because it is fast enough for just a download end point.
