### ISSUE TITLE
Check form_id is unique

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitServer#53]
ODK Collect only shows one form if the server has multiple forms with the same ID. Upon upload, check this, and inform the user if there is a problem (or automatically add a number at the end).

**Comment by danbjoseph** [comment]
- cards on /omk/pages/forms/ show the title and form ID
- in /omk/data/forms/ are only the filenames (as named when uploaded as xlsx)
- confusing when all three are likely different to have partially displayed in different places
- users often forget to update one or more and this causes problems
    - for example two forms were uploaded with the same form ID and in the interface clicking one opens both menus 
![screen shot 2016-12-05 at 3 42 47 pm](https://cloud.githubusercontent.com/assets/4806884/20901841/713fba58-bb02-11e6-89a5-af5befcc897f.png)
    - while clicking the other does nothing
![screen shot 2016-12-05 at 3 51 15 pm](https://cloud.githubusercontent.com/assets/4806884/20901888/adf2ac44-bb02-11e6-8105-b49b539200fd.png)

**Comment by danbjoseph** [comment]
I think my preferred solution would be to: 
- on upload show the user and have them confirm that the form_id, title, and filename are correct
- warn and reject if any of those already exist on the server (let them know which is a duplicate)

**Comment by mojodna** [comment]
Aha, it's possible to use an ID that differs from the filename:

![XLSForm](https://cloud.githubusercontent.com/assets/4806884/15805237/1588be94-2af2-11e6-87b8-90fdf7f36958.png)

**Comment by danbjoseph** [comment]
yeah... file name, form_id, and title can all be different

**Comment by mojodna** [comment]
I just refactored the upload process to be stricter about conflicts with existing forms.

If forms already exist with the same filename, title, _or_ ID, uploads will be rejected. I increased the timeout on the toast to 5 minutes so that error messages will stick around long enough to understand what happened.

I skipped showing values to the user and allowing them to confirm that values are correct as there's no good/easy way for users to take action on what's displayed (vs. the error messages, which will hopefully be clear enough to indicate what needs changing in the XLSForms).
