### ISSUE TITLE
Downloading CSVs creates an Excel file with HTML code

### ISSUE THREAD

**Issue by sirhornbeck** [AmericanRedCross/OpenMapKitServer#84]
When trying to download the CSV from a project, the system creates an Excel file with the HTML coding. I have attached an example of the file that is being downloaded (converted to xlsx for uploading purposes.
This is happening using Chrome and Firefox.

[data.xlsx](https://github.com/AmericanRedCross/OpenMapKitServer/files/418155/data.xlsx)

**Comment by danbjoseph** [comment]
This should be fixed with #83 just not yet pulled down to the instance we have running. In the meantime you can click 'view csv' then copy/paste into a plain text document and save with a csv extension.

![screen shot 2016-08-15 at 10 04 26 am](https://cloud.githubusercontent.com/assets/4806884/17666742/b3aac4f4-62cf-11e6-8aa0-de75ec839dbb.png)

**Comment by hallahan** [comment]
Closing. Reopen if the problem pops up?
