### ISSUE TITLE
Media document support (as part of questions, not responses)

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#88]
there should be a way to upload associated docs (form logos, media like pics for questions, etc)

to support for example:
https://opendatakit.org/help/form-design/data-preloading/
(which our formhub instance doesn't seem to support)

Specifically referring to http://xlsform.org/#media

**Comment by emilyeros** [comment]
FYI, if you upload an ODK form with a media attachment question type (e.g. "image"), it will bring the whole server down. To fix this, SSH in and delete the problematic form and XML.

When media document capabilities are added, this would be a good time to address this - for any question types that omkserver still can't handle, there should be an error message on upload to block the form.

**Comment by danbjoseph** [comment]
with this issue i was referring specifically to http://xlsform.org/#media
> You can include questions in your form that display images or that play video or audio files. 

if omkserver can't handle `image` type questions (where the user takes a picture) and also can't do signatures (`type`=`image` and `appearance`=`signature`) then that is another issue and a pretty major shortfall if omkserver is going to be used for general mobile data collection.

**Comment by danbjoseph** [comment]
support for image type question logged in issue #29

**Comment by mojodna** [comment]
On my dev copy, the "Malawi_MRI_images_break_server" form generates proper XML that can be read by ODK Collect. Filling out a form and attaching an image results in the attachment being stored in the `submissions` directory (although it's not visible or downloadable from the UI).

I need to do more investigation to understand why this doesn't work on POSM or either of the omkserver instances.

**Comment by mojodna** [comment]
Differences between dev and omkserver.xyz:

dev: `xlrd==0.9.4`
omkserver: `xlrd==0.8.0`
dev: `pyxform==0.9.18-89-ge486b54` (git submodule)
omkserver: `pyxform==0.9.22`

**Comment by danbjoseph** [comment]
- ODK page on media in a survey question: https://opendatakit.org/help/image-based-forms/
- also related: https://opendatakit.org/help/form-design/external-itemsets/
- also, i think if you include a `form_logo.png` image file, then ODK collect with display the image on the opening screen of the survey

**Comment by mojodna** [comment]
(Removed comments not relevant to this issue.)

**Comment by mojodna** [comment]
To do this, there needs to be a `media::image` column in the XLSForm containing the filename of something that can be loaded elsewhere.

OMKServer also needs to populate the `manifestUrl` option for `openrosa-formlist` in order to generate `manifestUrl` entries in the form list (when media is present). `/formList` should then contain:

```xml
  <xform>
    <name>Points of Interest 2</name>
    <formID>pois_2</formID>
    <hash>md5:c284bde2cbe3fc14cb747796b44af97e</hash>
    <downloadUrl>http://localhost:3210/omk/data/forms/pois2.xml</downloadUrl>
    <manifestUrl>http://localhost:3210/omk/odk/manifest/pois_2.xml</manifestUrl>
  </xform>
```

http://localhost:3210/omk/odk/manifest/pois_2.xml needs to be an additional endpoint that uses `openrosa-manifest` to generate a manifest, which ends up looking like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest xmlns="http://openrosa.org/xforms/xformsManifest">
  <mediaFile>
    <filename>test.png</filename>
    <downloadUrl>https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png</downloadUrl>
    <hash>md5:8f9327db2597fa57d2f42b4a6c5a9855</hash>
  </mediaFile>
</manifest>
```

`downloadUrl` is fake here because I haven't yet wired up the piece that finds attachments in the XForm (e.g. `<value form="image">jr://images/test.png</value>`) and translates them to valid URLs. External URLs (like this) do work, as ODK Collect will download them and store them locally as `<filename>`.

Still needed:

* the ability to upload files that complement the XLSForm
* filtering of uploads to ensure that they're referenced by the XLSForm (optional, since it can be abused in other ways)
* validating of uploads to ensure that all referenced resources were included
* map filenames in the XForm to `downloadUrl` entries that correspond to actual files

One shortcut that could potentially be taken is to assume that files are available from some other source (configured per OMKServer instance), but that's not particularly offline-friendly, so media attachments should be fully implemented.
