### ISSUE TITLE
Aggregate OSM submissions with Filter Funcationality (Partial Data Export)

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitServer#9]
for times when data is collected over multiple days but we want to do a rolling upload to OSM. it would be nice to have a way to export (or just get easily, through filtering in JOSM somehow) a subset of the osm file export

for example data collected on Tuesday is downloaded, conflicts resolved and it’s uploaded on Wednesday, more data collection on Thursday, want to get an osm file with only the new data submissions. can use the 'purge' advanced JOSM tool to have it forget selected data but you still have to be able to know which features are new and somehow select everything else.

**Comment by hallahan** [comment]
The original approach was to build out an API that queries OSM data in Spatialite in [OSMSpatialite](). However, we've decided to redirect our approach, and we instead are thinking about a workflow where we use osmosis and osmconvert to process the data. Right now, the thought is we want a preprocessing tool that will do some aggregating and filtering of the responses sent to OpenMapKit Server.

Take a look at https://github.com/AmericanRedCross/posm/issues/17

I'm researching how we want to do this and the limitations of different approaches. I'm documenting what I'm learning in that issue.

**Comment by hallahan** [comment]
I'm sprinting on this feature today. Tracked on:

https://github.com/AmericanRedCross/OpenMapKitServer/tree/aggregate-osm

**Comment by hallahan** [comment]
Note that one key parameter to filter by is user. Since day 1, OpenMapKit has put an OSM user in the the submission data, thinking ahead. I was actually just stubbing in my OSM user name...

```
https://github.com/AmericanRedCross/OpenMapKitServer/blob/aggregate-osm/test/fixtures/osm/basic/OSMNode-2.osm
```

The idea is that we will have a dialog in OpenMapKit Android ask for just the user name. The server can then filter the aggregation by server so we can do submissions for a certain user by a user.

**Comment by hallahan** [comment]
Ready to shred some code for filtering OSM Elements based on certain criteria as we aggregate OSM submissions.

This OSM aggregation and filter work is now in the /osm directory in the project. API endpoints import the aggregate module.

**Comment by hallahan** [comment]
I'm thinking it would be good to implement an OSM user input view on Android so that this can be included in submissions. Also, I'd like to make sure the OSM Elements get timestamps from when they are modified on the phones to help with @danbjoseph original request to filter by the time the data is collected.

I'm feeling good enough about the aggregation part of things to merge into master, and this functionality will be good for current field deployments right now. As it stands, you can have all of your submissions rolled up properly for a single JSOM import.

cc/ @danbjoseph @jj0hns0n @rbanick

**Comment by danbjoseph** [comment]
Hopefully the phones have the date/time set correctly but there's no guarantee. However, my initial request has to do with the subsequent upload to OSM via JOSM so I care about the timestamp for the data reaching the server so that I can filter what I haven't gotten the rest of the way to OSM, regardless of when the data was collected on a phone.

**Comment by hallahan** [comment]
OK, we should be able to filter by the timestamp of the file itself on the server as well.

**Comment by hallahan** [comment]
You can now filter by user like this:

<img width="1107" alt="screenshot 2015-12-30 17 42 16" src="https://cloud.githubusercontent.com/assets/556367/12060087/c14dfa98-af1c-11e5-8792-c0e543f83bfb.png">

You can filter everything that starts on a day like this:

<img width="1028" alt="screenshot 2015-12-30 17 46 09" src="https://cloud.githubusercontent.com/assets/556367/12060117/45b29c58-af1d-11e5-8974-c0ea089a66e9.png">

You can filter a range of dates like this:

<img width="982" alt="screenshot 2015-12-30 17 47 27" src="https://cloud.githubusercontent.com/assets/556367/12060125/6d2d5980-af1d-11e5-974c-597c79ce129f.png">

**Comment by hallahan** [comment]
And, you can put the full timestamp, something like this:

```
2015-12-26T21:38:50Z
```

Now we need to merge this puppy in and make a simple dashboard. I will open another issue about that.
